/**
 * Token types for the C- language (scanner).
 * Similar to ssheik08_a1: constants and string representation.
 * The parser uses sym.java (generated by CUP); this class is for reference and display.
 */
public class Token {

    // Keywords
    public static final int VOID = 1;
    public static final int INT = 2;
    public static final int IF = 3;
    public static final int ELSE = 4;
    public static final int WHILE = 5;
    public static final int RETURN = 6;

    // Identifiers and literals (with value)
    public static final int ID = 7;
    public static final int NUM = 8;

    // Operators
    public static final int ASSIGN = 9;   // =
    public static final int EQ = 10;      // ==
    public static final int NE = 11;      // !=
    public static final int LT = 12;      // <
    public static final int LE = 13;      // <=
    public static final int GT = 14;      // >
    public static final int GE = 15;      // >=
    public static final int PLUS = 16;
    public static final int MINUS = 17;
    public static final int STAR = 18;
    public static final int SLASH = 19;

    // Punctuation
    public static final int LPAREN = 20;   // (
    public static final int RPAREN = 21;   // )
    public static final int LBRACE = 22;   // {
    public static final int RBRACE = 23;   // }
    public static final int SEMI = 24;     // ;
    public static final int COMMA = 25;    // ,

    public static final int ERROR = 26;

    public int m_type;
    public String m_value;
    public int m_line;
    public int m_column;

    public Token(int type, String value, int line, int column) {
        m_type = type;
        m_value = value;
        m_line = line;
        m_column = column;
    }

    public String toString() {
        String name = typeName(m_type);
        if (m_value != null && !m_value.isEmpty() && (m_type == ID || m_type == NUM))
            return name + "(" + m_value + ")";
        return name;
    }

    private static String typeName(int type) {
        switch (type) {
            case VOID:    return "VOID";
            case INT:     return "INT";
            case IF:      return "IF";
            case ELSE:    return "ELSE";
            case WHILE:   return "WHILE";
            case RETURN:  return "RETURN";
            case ID:      return "ID";
            case NUM:     return "NUM";
            case ASSIGN:  return "ASSIGN";
            case EQ:      return "EQ";
            case NE:      return "NE";
            case LT:      return "LT";
            case LE:      return "LE";
            case GT:      return "GT";
            case GE:      return "GE";
            case PLUS:    return "PLUS";
            case MINUS:   return "MINUS";
            case STAR:    return "STAR";
            case SLASH:   return "SLASH";
            case LPAREN:  return "LPAREN";
            case RPAREN:  return "RPAREN";
            case LBRACE:  return "LBRACE";
            case RBRACE:  return "RBRACE";
            case SEMI:    return "SEMI";
            case COMMA:   return "COMMA";
            case ERROR:   return "ERROR";
            default:      return "UNKNOWN";
        }
    }
}
